function SetAdvancedImageProcessingLabText(handles )
string = { 'Advanced Image Processing Lab'};
axes1_children =  get(handles.axes1 , 'children');
if ( ~strcmpi(get(axes1_children, 'type'), 'image') )
    imshow(imread(fullfile(ScriptCurrentDirectory, '..', 'Data', 'lenna_all.png')), 'parent', handles.axes1);
end
text('parent', handles.axes1, ...
    'string', string, ...
    'units', 'normalized', ...
    'Clipping', 'off', ...
    'interpreter', 'latex', ...
    'position', [0.5 0.7], ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment', 'top', ...
    'Visible', 'on', ...
    'fontsize', 26, ...
    'color', 'w', ...
    'BackgroundColor', 'k',...
    'fontweight', 'bold');
string = { 'Created By: Moshe Bouhnik', 'Mail: moshe.bou@gmail.com', 'Supervised By: Prof. Leonid Yaroslavsky'} ;        
text('parent', handles.axes1, ...
    'string', string, ...
    'units', 'normalized', ...
    'Clipping', 'off', ...
    'interpreter', 'latex', ...
    'position', [1 0], ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment', 'bottom', ...
    'Visible', 'on', ...
    'fontsize', 16, ...
    'color', 'w', ...
    'BackgroundColor', 'k',...
    'fontweight', 'bold'); 

function scd = ScriptCurrentDirectory
    scd = mfilename('fullpath');
    scd = scd(1:end - length(mfilename));