function buttongroup = SetTopicsRadioButtons( TopicList, FunctionHandle, Position, Parent )       
    NumTopics = length(TopicList);
    num_of_lines = length(TopicList);
    is_two_lines = false(1, NumTopics);
    Parent_units = get(Parent, 'units');
    set(Parent, 'units', 'pixels');
    Parent_pos = get(Parent, 'position');
    set(Parent, 'units', Parent_units);
    buttongroup_position_pix = Parent_pos(3)*Position(3);
    font_size = 9;
    for i = NumTopics:-1:1 
        curr_string = TopicList{i};
        curr_string_length = length(curr_string);        
        string_len_pix = estimate_string_length_pixels( curr_string, font_size);
        string_len_pix = string_len_pix +6*string_len_pix/curr_string_length;
        if(  string_len_pix > buttongroup_position_pix )
            num_of_lines = num_of_lines +1;
            is_two_lines(i) = true;
        end
    end
    
    Position(4) = num_of_lines*Position(4)/2;
    
    buttongroup = uibuttongroup( ...
                'parent', Parent, ...
                'units', 'normalized', ...
                'position', Position, ...
                'selectionchangefcn',   FunctionHandle, ...
                'visible', 'on');
    Parent_units = get(Parent, 'units');
    set(Parent, 'units', 'points');
    Parent_position = get(Parent, 'position');
    set(buttongroup, 'units', 'pixels');
    buttongroup_position_pix = get(buttongroup, 'position');
    set(buttongroup, 'units', 'normalized');
    buttongroup_position_norm = get(buttongroup, 'position');
    buttongroup_width_points = 1.75*Parent_position(3)*Position(3);
    for i =  NumTopics:-1:1
        if(  is_two_lines(i) )
            if ( i == NumTopics ) 
                y = 0;
            end
            radio_button(i) = uicontrol(...
            'Style', 'radiobutton', ...
            'tag', TopicList{i}, ...
            'parent', buttongroup, ...
            'FontWeight',  'bold', ...       
            'fontsize', font_size, ...                    
            'units', 'normalized', ...
            'position', [0 y 1 2/num_of_lines]); 
             tmp2 = uicontrol('style', 'text', ...
                        'parent', buttongroup, ...
                        'HorizontalAlignment', 'left', ...
                        'visible', 'on', ...
                        'units', 'normalized',...
                        'fontsize', font_size, ...
                        'FontWeight',  'bold', ...
                        'Enable', 'Inactive', ...
                        'ButtonDownFcn', FunctionHandle, ...
                        'parent', buttongroup, ...
                        'position', [buttongroup_position_pix(4)/(buttongroup_position_pix(3)*NumTopics) y (1-(1/NumTopics)) 2/num_of_lines], ...
                        'string', TopicList{i});
             y = y + 2/num_of_lines;
        else
            if ( i == NumTopics ) 
                y = 0;
            end
            radio_button(i) = uicontrol(...
            'Style', 'radiobutton', ...
            'string', TopicList{i}, ...
            'parent', buttongroup, ...
            'FontWeight',  'bold', ...       
            'fontsize', font_size, ...                    
            'units', 'normalized', ...
            'position', [0 y 1 1/num_of_lines]);
            y = y + 1/num_of_lines;
        end
    end
    set(buttongroup, 'SelectedObject' , radio_button(1));
end