function val = SliderOper(operation, params )
global Slider
switch operation
    case 'display'
        Slider.slider = uicontrol( ...
                    'Style', 'slider', ...
                    'Units', 'normalized', ...
                    'position', params.slider.position, ...
                    'visible', params.slider.visible, ...
                    'Min',params.slider.min,'Max',params.slider.max,...
                    'Value',params.slider.value,'SliderStep',params.slider.sliderstep, ...
                    'callback', params.slider.callback);
           Slider.text1 = uicontrol( ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'position', params.text1.position, ...
                'visible', 'on', ...
                'fontsize', 8, ...
                'FontWeight',  'bold', ...
                'string', params.text1.string);            
            align(Slider.text1,'VerticalAlignment', 'middle');
            Slider.text2 = uicontrol( ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'position',params.text2.position, ...
                'visible', 'on', ...
                'fontsize', 8, ...
                'FontWeight',  'bold', ... 
                'string', params.text2.string); 
            align(Slider.text2,'VerticalAlignment', 'middle');
            val = Slider;
    case 'update'
        if ( isfield(params, 'slider') && ~isempty(params.slider))
            sliderfieldnames = fieldnames(params.slider);
            for i=1:length(sliderfieldnames)
                set(Slider.slider, sliderfieldnames{i}, params.slider.sliderfieldnames{i});
            end
        end
        if ( isfield(params, 'text1') && ~isempty(params.text1))
            text1fieldnames = fieldnames(params.text1);
            for i=1:length(text1fieldnames)
                set(Slider.text1, text1fieldnames{i}, params.text1.text1fieldnames{i});
            end
        end
        if ( isfield(params, 'text2') && ~isempty(params.text2))
            text2fieldnames = fieldnames(params.text2);
            for i=1:length(text2fieldnames)
                set(Slider.text2, text2fieldnames{i}, params.text2.text2fieldnames{i});
            end
        end
    case 'get'
        val = get(params.handle, params.field);
%     case 'delete'
%         clear -global Slider.slider
%         clear -global Slider.text2
%         clear -global Slider.text1
end